version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: stori_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stori
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d stori"]
      interval: 5s
      timeout: 3s
      retries: 10

  db_test:
    image: postgres:16-alpine
    container_name: stori_db_test
    environment:
      - POSTGRES_USER=stori
      - POSTGRES_PASSWORD=stori
      - POSTGRES_DB=stori_test
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stori -d stori_test"]
      interval: 2s
      timeout: 2s
      retries: 30

  app:
    build: .
    container_name: stori_app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - go-mod:/go/pkg/mod
      - go-build:/root/.cache/go-build
    command: ["air", "-c", ".air.toml"]

volumes:
  pgdata:
  go-mod:
  go-build:
  pgdata_test:


